# See https://gitlab.liris.cnrs.fr/pagoda/tools/mkdocs_template/-/blob/master/user_config/pyproject.toml

# -----------------------------------------------------------------------------
# Pytest configuration
# https://docs.pytest.org/en/latest/customize.html?highlight=pyproject#pyproject-toml
[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--cov=sparse_caption"
filterwarnings = [
    "ignore:Using or importing the ABCs from 'collections' instead of from 'collections.abc'",
    "ignore:Call to deprecated create function FileDescriptor",
    "ignore:Call to deprecated create function FieldDescriptor",
    "ignore:Call to deprecated create function Descriptor",
    "ignore:Call to deprecated create function EnumValueDescriptor",
    "ignore:Call to deprecated create function EnumDescriptor",
]

# -----------------------------------------------------------------------------
# Black (Option-less formatter) configuration
# https://black.readthedocs.io/en/stable/index.html
[tool.black]
line-length = 120
target-version = ["py37"]
include = "\.pyi?$"
